[tool.poetry]
name = "dezero"
version = "0.1.0"
description = "Deep Learning Framework for Python from Scratch."
authors = ["りーべ <magical.liebe@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10,<3.11"
numpy = "^2.0.0"
single-source = "^0.4.0"

[tool.poetry.dev-dependencies]
black = "^24.0.0"
pyproject-flake8 = "^7.0.0"
flake8-isort = "^6.0.0"
flake8-annotations = "^3.0.0"
flake8-docstrings = "^1.6.0"
mypy = "^1.0"
pytest = "^8.0.0"
pytest-sugar = "^1.0.0"
pytest-cov = "^6.0.0"
poethepoet = "^0.32.0"
pre-commit = "^4.0.0"
nptyping = "^2.1.1"

[tool.poe.env]
package = "dezero"

[tool.poe.tasks]
    [tool.poe.tasks.run]
    help = "Run Python"
    cmd = "python"
    [tool.poe.tasks.lint]
    help = "Run flake8 on the code base"
    sequence = [
        {cmd = "pflake8 ${package}/*.py tests/*.py"},
        {cmd = "mypy ${package}/*.py tests/*.py"},
    ]
    [tool.poe.tasks.fix]
    help = "Run black on the code base"
    cmd  = "black ${package}/*.py tests/*.py"
    [tool.poe.tasks.test]
    help = "Run unit and feature tests"
    cmd = "pytest -v --cov ${package} --cov-report term-missing"

[tool.black]
target-version = ['py310']
line-length = 120

[tool.flake8]
max-line-length = 120
extend-ignore = "E203,W503,W504,ANN101"
max-complexity = 15

[tool.mypy]
python_version = "3.10"
no_strict_optional = true
ignore_missing_imports = true
check_untyped_defs = true

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
